version:
  name: velociraptor
  version: 0.6.6-2
  commit: ebaf185
  build_time: "2022-09-10T01:52:02Z"
  ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/3026320201
  compiler: go1.18.4
Client:
  server_urls:
  - https://192.168.1.88:4300/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDSzCCAjOgAwIBAgIQXSG4xzm+MEIWoTBHqPzyoDANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjIwOTI2MDU0ODE3WhcNMzIw
    OTIzMDU0ODE3WjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCpvuzpEM+Dj1Kbo9/FMnvYjYuraosuhyb4
    9s0CpwowHMCfEpBdt35hwRHM0KgB39dQhVCzdV4bGP+XnmK4Xao/20nHc7jcU+Oi
    CaQVE6O6tjqZDRgb2nDjRJb/iDU8kDJv/8y8Y4oZ9k0xtEgQP+qFgts1yzJAlNyt
    eWvypm56GuMzsZUTk1mzIRkBNDIUg1TJvEJUnxXQYU1hx/3Vi+THoBCtyHsIKd/i
    xqYfvZOQmsGpebGKQ9AhXq/p0W46vrCk0AdJ8Mjfq2Y2uHnvbfe4RkdUXZVUJMOP
    fAmqY/fHPewMtLCzE2KMgJ4JxsvhYrbB6cmmbRqe840oahjCTjk9AgMBAAGjgYww
    gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
    AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBShyHDM1FZyvoC8RhrXu5NM2SXI
    1DAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
    hkiG9w0BAQsFAAOCAQEAcjuBthbatpRlxGf5Owhdg6nRLoaDrhop7wi4aYxQU9i5
    XNe196Sv/4+9DDAamSnIBIDyXJe40gX1Ck9Avknaeal3IJzK20g+z7l6xOQxOg+9
    KZ7KOP4QGA2Klg0e2zH+bvkMIlNCoIZhsdjKyv750xZ3WF2wM7ob/vARaYgRwUjb
    rStMnFglJLmwOznH+CeySbIpWNVS+T8+kqfL6mBz60ke4bLh714UJlmIe8Uf7K+r
    LgQmOskfrxxVOBZYYL80hQlLvW1SH+EbvZ0l+PLglmIh82ACXVM9iaxPMF1g0+bc
    JiHYPyDPE3ve76in3ATqPO1EJr1ifHz16Nvc+I8C1g==
    -----END CERTIFICATE-----
  nonce: lWPW+ggErY4=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.6.6-2
    commit: ebaf185
    build_time: "2022-09-10T01:52:02Z"
    ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/3026320201
    compiler: go1.18.4
  use_self_signed_ssl: true
  pinned_server_name: VelociraptorServer
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
