version:
  name: velociraptor
  version: 0.6.6-2
  commit: ebaf185
  build_time: "2022-09-10T01:52:02Z"
  ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/3026320201
  compiler: go1.18.4
Client:
  server_urls:
  - https://192.168.1.88:4300/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDSzCCAjOgAwIBAgIQXSG4xzm+MEIWoTBHqPzyoDANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjIwOTI2MDU0ODE3WhcNMzIw
    OTIzMDU0ODE3WjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCpvuzpEM+Dj1Kbo9/FMnvYjYuraosuhyb4
    9s0CpwowHMCfEpBdt35hwRHM0KgB39dQhVCzdV4bGP+XnmK4Xao/20nHc7jcU+Oi
    CaQVE6O6tjqZDRgb2nDjRJb/iDU8kDJv/8y8Y4oZ9k0xtEgQP+qFgts1yzJAlNyt
    eWvypm56GuMzsZUTk1mzIRkBNDIUg1TJvEJUnxXQYU1hx/3Vi+THoBCtyHsIKd/i
    xqYfvZOQmsGpebGKQ9AhXq/p0W46vrCk0AdJ8Mjfq2Y2uHnvbfe4RkdUXZVUJMOP
    fAmqY/fHPewMtLCzE2KMgJ4JxsvhYrbB6cmmbRqe840oahjCTjk9AgMBAAGjgYww
    gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
    AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBShyHDM1FZyvoC8RhrXu5NM2SXI
    1DAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
    hkiG9w0BAQsFAAOCAQEAcjuBthbatpRlxGf5Owhdg6nRLoaDrhop7wi4aYxQU9i5
    XNe196Sv/4+9DDAamSnIBIDyXJe40gX1Ck9Avknaeal3IJzK20g+z7l6xOQxOg+9
    KZ7KOP4QGA2Klg0e2zH+bvkMIlNCoIZhsdjKyv750xZ3WF2wM7ob/vARaYgRwUjb
    rStMnFglJLmwOznH+CeySbIpWNVS+T8+kqfL6mBz60ke4bLh714UJlmIe8Uf7K+r
    LgQmOskfrxxVOBZYYL80hQlLvW1SH+EbvZ0l+PLglmIh82ACXVM9iaxPMF1g0+bc
    JiHYPyDPE3ve76in3ATqPO1EJr1ifHz16Nvc+I8C1g==
    -----END CERTIFICATE-----
  nonce: lWPW+ggErY4=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.6.6-2
    commit: ebaf185
    build_time: "2022-09-10T01:52:02Z"
    ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/3026320201
    compiler: go1.18.4
  use_self_signed_ssl: true
  pinned_server_name: VelociraptorServer
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
API:
  hostname: 192.168.1.88
  bind_address: 127.0.0.1
  bind_port: 8001
  bind_scheme: tcp
  pinned_gw_name: GRPC_GW
GUI:
  bind_address: 127.0.0.1
  bind_port: 4200
  gw_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDQTCCAimgAwIBAgIQVwBowsEm+0FW8bPMnqluSTANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjIwOTI2MDU0ODE3WhcNMjMw
    OTI2MDU0ODE3WjApMRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxEDAOBgNVBAMMB0dS
    UENfR1cwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDzPZoFW3M7qNCM
    9WNuJYR9RybMR10bttExnar0nItTxdZYQZaT5yaBNdOYPqdLBJvQHTvbDD5m85si
    +a9FHTdJn3t5qMlnZQYjScewwZNLuJUwvL9geRovNHNokBfOxVD5VSpJvb2QGBFE
    wXciVO1pQbdfM0WKQninUkHFKndmOhs1a3G8WHIW6t7yaPVbJK0vTpaDl2WXOLcX
    2aTD7gibc3JQwDEg87VJFLOIs+oZ3JZvz+prhBhkorRbPz8KHAKyLrU7Fk6MlBcj
    JdaD+A/ewK3Sf9WEDJAshB0xFWw6lnKH95CyNBBDre21TaQ6E7MjAUKzeVpycZvL
    Koj4lXaZAgMBAAGjdDByMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEF
    BQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBShyHDM1FZy
    voC8RhrXu5NM2SXI1DASBgNVHREECzAJggdHUlBDX0dXMA0GCSqGSIb3DQEBCwUA
    A4IBAQAfYLdJIKQ4IJc+P/cD7seFKOcbZ+xSPEdOWvWpetFkfWBuCvGCihn+mPXP
    05ajanI6z7qUEvLbFYUpnLffzJ+JMz5oLcvwSqbcJSDCZ+LL0L8IhDSsZ17zFf8I
    hCAejuMCMQn1icDP5CpnVSfMVZE7IkDpjlV1ooZOsuOUetEn0/LCocEBwinUh3Ue
    YsQgNDhCf6wyJ2JsCEWQZzKLSDeh/c2ALIOendzx7Dy8uorPZcS8OwRGMK2RPhng
    CZlID49Hfs8NMjJr6xrp9tNCmKq56MMXgaqIGXmPicum1Qvs1ksfKFEz+rbELaJm
    pMqpTXK8nseW/+NFFj1eCKk8ra++
    -----END CERTIFICATE-----
  gw_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEA8z2aBVtzO6jQjPVjbiWEfUcmzEddG7bRMZ2q9JyLU8XWWEGW
    k+cmgTXTmD6nSwSb0B072ww+ZvObIvmvRR03SZ97eajJZ2UGI0nHsMGTS7iVMLy/
    YHkaLzRzaJAXzsVQ+VUqSb29kBgRRMF3IlTtaUG3XzNFikJ4p1JBxSp3ZjobNWtx
    vFhyFure8mj1WyStL06Wg5dllzi3F9mkw+4Im3NyUMAxIPO1SRSziLPqGdyWb8/q
    a4QYZKK0Wz8/ChwCsi61OxZOjJQXIyXWg/gP3sCt0n/VhAyQLIQdMRVsOpZyh/eQ
    sjQQQ63ttU2kOhOzIwFCs3lacnGbyyqI+JV2mQIDAQABAoIBAQDoa+5mPBIJ6a8N
    YdTWhObqRjiebXpcZv3RaRTXk1XWgG3l+xYE0ZSLVoGPMh7socS4wZZWIobmHNQa
    QXbmlZoksU1s3IlGUNPimDdFgFJcwk1cOp6rckxA2t+EBFubahOLi4NS3wjpTPYD
    OtG5bmlEcFTllLpX+FgNmZ3a5k8cz4AL8Xnv3b1ScFB8jouaJkX2/Vi8+0VE/06P
    WdseoDQwuyjp0O7Wh/5AOzafOzxIk25FDTWAH2hFuBzV7ld0a41cjlDhL9TQ1PFJ
    aC179WqMKhehiFulWRtQkIRXTddQtKc9Z1HiP8vIf3I5fJjioI7rlpyhXXU44aSC
    OxJYGmIBAoGBAPXhT1kqI4x7k1tr6S+iLYYV7hEIgKkGgcJ756saHunL2Av6Ay8P
    M+I+cQnpYDuCA1veT1IKVaM4LCjRY3DtgcC5mneluRzyeTYHJrzxuZeKKKIYSaIL
    AqlGlevvVyhEBHuwLCT7NJGymAqZNCvSGQfIxOAYYSulnopazZNq2RF5AoGBAP1A
    eySXs8ao5jLAL15Xge6v/Z3xMynk6ter5RzHBlq2ho1kS3kQzCio/rtlMAlU5Wha
    K0SPw8y1vtGqCvmnegdU/oHB3xpUi1LtNQqwuHqhLzi87zQk+kyiTIYbxd/1tCHS
    /ByrrwaS77oDXy2AHfvHk3NwvgHBxFZfI069xGYhAoGBAOSfOBF3PhCcwrppzyus
    R1n6wB50YnVHiJXWceXFZuMK1/ri39z87Mg8OQz3Q7RxQkBEqEpnM5ONYnodn7Hc
    FR6nNXp0zHee+ZeD9MAQnvnJy9hUbvrN9A6DhFkZdVgKToTXnWRRc2LZxcdtBnaM
    Zxu20WBxKsDTwWNx5N5ipi05AoGAFb6ClDq+QdFgqnzb1FLZIiBUO0ppZTB1hX0J
    1/Wysvk3Bk7VOBjcHqWb8YUXocV7SQFs858QZbQ5JRFfjd32WUjP7V4zBLS7nawm
    QLu5qzXJsypts2F1aD0LKvyZechD5h+Sa/fFuF/HW4ZMlsCIUoTpQSEt/0Ke0/ep
    NWqPwWECgYAMHNvdqT7hIqpIhi5BYs21ad5/fu/Lg0weurUeidIKUvpyS91eMj95
    Mn4iC5XX1/bb4kQ93w6OmAcsrRY0b+G0nuwBy7F5m8Tkk1CfvG9pIHyAT2bjWWRY
    cb+EPxKRx9oNL+cYJLOLO4a4ll+QJfY5f26WWz7oWAywlvrsQ7fnTg==
    -----END RSA PRIVATE KEY-----
  initial_users:
  - name: admin
    password_hash: a0a7a6ab14fd385b8ec62452310fea890255d622beecdb231e908c55c05566cf
    password_salt: 6b9ae7424aabb43a76209a4e20c83aa702a5c8ab381e304f0d669dd49879fac7
  authenticator:
    type: Basic
CA:
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAqb7s6RDPg49Sm6PfxTJ72I2Lq2qLLocm+PbNAqcKMBzAnxKQ
    Xbd+YcERzNCoAd/XUIVQs3VeGxj/l55iuF2qP9tJx3O43FPjogmkFROjurY6mQ0Y
    G9pw40SW/4g1PJAyb//MvGOKGfZNMbRIED/qhYLbNcsyQJTcrXlr8qZuehrjM7GV
    E5NZsyEZATQyFINUybxCVJ8V0GFNYcf91Yvkx6AQrch7CCnf4samH72TkJrBqXmx
    ikPQIV6v6dFuOr6wpNAHSfDI36tmNrh57233uEZHVF2VVCTDj3wJqmP3xz3sDLSw
    sxNijICeCcbL4WK2wenJpm0anvONKGoYwk45PQIDAQABAoIBAFxIJOoMLpS6XVGq
    BKRjbrrrMMxvLt2Lsl9VZV0UzNAdQYb5g6y/biDc4r1zjnL+a0MmRxpZK2EV9RZL
    kCXlHgJ7SB/7xLtbi/xyu1aOB8wg97hvSvURi5+ykVi4hyC20ATdj0O35cN5iLwF
    48uZw/jzjBMxtc8wXsycn1garSMKCl/pA1fKIonWfRgY1mv80yBioYsoEpcGi2iJ
    U2D1hHOwjOPWQq2GRoJxSRrq3mYJTaFNCGTzwf717gsXfIedanE4jVmmcVla7cSC
    GbX8rAgSO6ocqLjlVH9vn2/nFqUPzHg0HRluD6W+XHGs0j1k72RvRinvb1wOS2re
    +scBK00CgYEAze4kdukt0LD99yLG4FWjsInNpfkSRTwVF4C4GJboqhEonnK2N+Wl
    rIufPCDZqGJORAoN8eFP3/nCW2i6+Sfrv5mqs3XkrehKnbPYid4jVpecA/oRfg/h
    bS4KC3R2cF0/URO1lAl7hkLwVEuHGliNj7UnnTyHeZ/phYrPKpE/FZ8CgYEA0wSH
    q282byKBlOnUktDOVOyQfi51cXnP7s9nI2bEeNzmZS/Y14njvck9yriGt7xdqmdK
    +OAgaiOhcE+HIz+LeGv1a36pDP4doT+WMeW3zPHNNNfpvASyEKhVS+DhawRoWHPS
    ly4M6dGDkai94T4OMJp7H1IfymaZ8e/UTJyma6MCgYEAr5+tkYwD+rs3nJEYMzJW
    S7T6odXtcwZupoCsgKwS+RdxINCL/tfnl2PsBYeumSBdx0Eb63FQgZ+r1fFXpC4b
    rGgNYMfmozo8iIpc3heI48ygzfNy/6PjiQ1+m45ThDjCSw8YCIydwD9OX1WafymO
    cUT55+s7TsrGiZF8ZL1Co9kCgYEAxoPedkMbvJWDvmn0V2IkmfQrQunGBskH+qwX
    ZVCKyQFXph3LK4pHPAYUIaBS7ItCusqN13BSTkfS2muWwGxJczJtIYF43AY8LbQ6
    QhrQPPfFi08MTptEQTN7evTGW/07hOsBVMQ31cgKtH9AkqPkiYjrB14lFi5L6TUs
    Th6Y2W0CgYBFRVS0o4Jj4vyuWEIaWxNSCf9YC635kJUC/nuWnHu3le8nr8MFLhGv
    LVwnNSbWJ5XTXNDxUJHoA+J2l4x6EYLSRgouRQhkxwKs8A0Nu0D4gRAEcOf1YNRw
    TqxkxDxXxPVz9k64vHvzYDxVwBNRJsAo/0FoBy9mYpO43VDPHqUvRA==
    -----END RSA PRIVATE KEY-----
Frontend:
  hostname: 192.168.1.88
  bind_address: 0.0.0.0
  bind_port: 4300
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDWDCCAkCgAwIBAgIRAOKqiKVcuXLVrIMMy392sZwwDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTIyMDkyNjA1NDgxN1oXDTIz
    MDkyNjA1NDgxN1owNDEVMBMGA1UEChMMVmVsb2NpcmFwdG9yMRswGQYDVQQDExJW
    ZWxvY2lyYXB0b3JTZXJ2ZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
    AQDM93CxX2G6529KIQlBp1SDl68CgtCDs2EUEW9MnudoT++aEQL8WqIjd/8Uf7l0
    2N3EWMhWDmMrwRDZ6RGyWuPG+gHBR29Nlt81qPc0QtBDcetVGzsDIW8IqEPx6QDJ
    cyPmAmadXVOhpwzaURIAiHWoM1y6kl/pe8LC+sUxGpqHf1AV2VyKJGmzFYY6voIn
    yGbjHWKMXol8aVyAW3SJm/T5POpDXFfc719d3zfQz/NAuswgssshwxfdY5XzdFJV
    x8ridLYsHS/ju6rFXozXic3KBGfeHxFpIgRVs2/m+gwIvTX+o7VdsMMrYDGI98rN
    9m6Th3JpdYcKNMm4LM4sD+jDAgMBAAGjfzB9MA4GA1UdDwEB/wQEAwIFoDAdBgNV
    HSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAfBgNVHSME
    GDAWgBShyHDM1FZyvoC8RhrXu5NM2SXI1DAdBgNVHREEFjAUghJWZWxvY2lyYXB0
    b3JTZXJ2ZXIwDQYJKoZIhvcNAQELBQADggEBAEnY0kExyOUcarOXVBofIJP4WihH
    CZ+dkbC7vJptVkwzTh5yvN/4F/6qTaOwkrMCecRzvhJT3WIRjaDr1wx4qpCHsopX
    IgomHu9XMhXdXgM7nry1kxkWoTtbTFMGfgV2yJH4c/P7IHrqMiPpLue0WIbi7wMf
    8d0LdGoZCGl+vtXtLCaJH1LQf+G0wH7DD240S7YMhwl+Fj2PzYHukMJZ1u6gGl+w
    qb3m5MLdIyFaNSYxax2jh/Zw4MgZzDozgoELW3cCaR/PQaQLFiqSJV76Pw/SLPqR
    I+Tj7Ylat4GNIXJLPwXCUxfxcYgMqP6copu3dhvoXua7KkUO6WtlDgWf30I=
    -----END CERTIFICATE-----
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAzPdwsV9huudvSiEJQadUg5evAoLQg7NhFBFvTJ7naE/vmhEC
    /FqiI3f/FH+5dNjdxFjIVg5jK8EQ2ekRslrjxvoBwUdvTZbfNaj3NELQQ3HrVRs7
    AyFvCKhD8ekAyXMj5gJmnV1ToacM2lESAIh1qDNcupJf6XvCwvrFMRqah39QFdlc
    iiRpsxWGOr6CJ8hm4x1ijF6JfGlcgFt0iZv0+TzqQ1xX3O9fXd830M/zQLrMILLL
    IcMX3WOV83RSVcfK4nS2LB0v47uqxV6M14nNygRn3h8RaSIEVbNv5voMCL01/qO1
    XbDDK2AxiPfKzfZuk4dyaXWHCjTJuCzOLA/owwIDAQABAoIBAQCZnPUTqjWXm243
    82x5jQv1F9BtJFdb7Stbm/l7RjiOYCJlqExBjzenN36wAU2f+gyy5As5G81NdIPJ
    nTjLH/1IGgUIsx4C24jsMXcb7tshQRarkR34Ka2KonlRq1wQnr+P2crIM7LDG2yx
    jkLcrWjop53eomdJmJyN/t2dAKBB3Vvi5VHRi87DJ8LmgKCckGHIb7bSANj1ftjW
    A2JiD6rrweP9gv6WVPRGKWsn/jz89/3OKUKU9m9r85djRh0ugOIFVwRedN+/C6Aa
    Ue4ItdVhPXQ275/Z5SRufdAVyZ4WDMZlSDD6hJrf8V2fmnU9O3e7FbDpGyFiQ0bE
    v2cHBrsJAoGBANhw6QwhYsTMs0Zh8YgRmybHrso+VsL6vDz7uj4VdKD/kK2CRdNf
    FBdPdCUpOhjZfk2EGhCsD3m6LLgWWzdKYfpP8fWYhLDlANP65kndzrjU2mJvJn3U
    uipz1YDdZJ0TMt/IFvqcbMmbgS2tlJ4IvhJpN1drDkwOMgqdmmlFcIUPAoGBAPJt
    pfXnGoIFaIpAreBD4ZcvjEQJtm5lKC7XnAumbGyYQrsw7u0kf5qJTIyqnIul7/Og
    Y//bY3cDkRSF6Irq99EnpzjyPWzKL26DiJ7Rnpz7MgJIix6Tt7wCPi0lcD2uVYqp
    XjXtcJUrgbtuOdVxttybqDRkoyVA27/0ByPQ2mkNAoGASCDYiQJXN94/oCTjqMS1
    P6cryJodr7x/HpOE7UuZIk4ImMnhGx+EQoBn5Dpo8f8I6Cwtw4CTZ61zWaWZoENZ
    g2FA8Ody0MCAFiR2ugcA7PeCD2ubGDPcFmmjrN4auX28Znb3sWyPlGAOHHrMHB4t
    uVT27Frw2MeiRYdf/dT2OmECgYEAvO2awtLCI8YXPHc/imEcc/hINdXj6JDJCghZ
    wfKG2PKoPr3Z1dH15/dMQuvLaEF/iLvccs8E6wFKlVXubiTD0Ko4dfbCy/+di2DS
    ngL6u5g/1uu2D7RLIigVUJW2rTspyxBHLXvHm1j2l51FUQR33+Em6v3q7uNm3mdN
    ESp4rBkCgYA/2H2TZJ+iGgev/XxcoCsLLEt6W3tX7BqCC+gKb+7Rln15jB5OvtWq
    3m14gi22UyKn5R/jpJ8EHRbaT7LyksCGSs4MuV1GZy32iLFeTrhtpw8RdUiHZQwd
    onu8qiwynsvUIo10he/wZH3vsQd+2JLu0FCZcis+GDrpedjk020FDA==
    -----END RSA PRIVATE KEY-----
  dyn_dns: {}
  default_client_monitoring_artifacts:
  - Generic.Client.Stats
  GRPC_pool_max_size: 100
  GRPC_pool_max_wait: 60
  resources:
    connections_per_second: 100
    notifications_per_second: 30
    max_upload_size: 10485760
    expected_clients: 30000
Datastore:
  implementation: FileBaseDataStore
  location: /opt/velociraptor
  filestore_directory: /opt/velociraptor
Logging:
  output_directory: /opt/velociraptor/logs
  separate_logs_per_component: true
  debug:
    disabled: true
  info:
    rotation_time: 604800
    max_age: 31536000
  error:
    rotation_time: 604800
    max_age: 31536000
Monitoring:
  bind_address: 127.0.0.1
  bind_port: 8003
api_config: {}
server_type: linux
obfuscation_nonce: kQOgyy5A5rE=
defaults:
  hunt_expiry_hours: 168
  notebook_cell_timeout_min: 10
