version:
  name: velociraptor
  version: 0.6.6-2
  commit: ebaf185
  build_time: "2022-09-10T01:52:02Z"
  ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/3026320201
  compiler: go1.18.4
Client:
  server_urls:
  - https://1f97-81-34-153-46.eu.ngrok.io/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDSzCCAjOgAwIBAgIQbkZ7PeO9RDVvczVZEiXkZTANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjIwOTE5MjE0MTI5WhcNMzIw
    OTE2MjE0MTI5WjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDEVip+FICx1wqX8hgTIoVPiLcIxQO74WYM
    HLVsD86wxrXwZDwd/AM2bm0/5D3OwpcmZWDEO0I40qrs+dFc9hQARZRjECKAU/TC
    BfCmleXgbCKCgEnd+hAanuMofDAOF8Iowr98V6cWm8o0dKGdy9lrtxiVXrGo5kVW
    MxBmF0Aq/3vi+1TugZQj4o4XcIi0IhJC3ZrBkl23gndveSGnrrq0MxV7cXEKlbIJ
    jil5vUgs5CkqLeCoPgQu7OL/FtB0GDu331x1d6vrc1qrKauGbHH7dz4uw1S0KLVH
    9gI24Wy3dE11WTKPIKa1w9v46DAr0IOCZ4WIUqPhUCj5yy5ykmNrAgMBAAGjgYww
    gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
    AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQYuLj0TW27JacaceZQp4VDryKb
    7jAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
    hkiG9w0BAQsFAAOCAQEADYTWcxLpudDRh8dxrDeKKjEyY5qTCOOkL9M5zhmyrYkl
    Dxic/UOb9Jn9Vh+bkcmHsp4IAtR/3R8U9ICeD2LLP3D33575/J6FxD3PDDgdbZLL
    C8HGyiYFFSMDfcqMei+TNcrr3si6hHuLU/oBULFr0L/Qaj6hKjhIauUWuEmvCItX
    qg57QdrrOt64SiaEFZbq52ce9a9KttTlOgzKUBFTlb/PFK4JEmpr+yjAXgikgLOl
    J3QVeWlK6R79WDyFrWxjANAgj6is9SUzNWNuhicLvDir9UwJpwt+XYyIBqMnfX0G
    94rHA+kIBk+DLC6xtih/Yx0IjFAzcY205InVF9Ynng==
    -----END CERTIFICATE-----
  nonce: XaBf/i04NJ0=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.6.6-2
    commit: ebaf185
    build_time: "2022-09-10T01:52:02Z"
    ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/3026320201
    compiler: go1.18.4
  use_self_signed_ssl: true
  pinned_server_name: VelociraptorServer
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
API:
  hostname: localhost
  bind_address: 127.0.0.1
  bind_port: 4201
  bind_scheme: tcp
  pinned_gw_name: GRPC_GW
GUI:
  bind_address: 127.0.0.1
  bind_port: 4200
  gw_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDQjCCAiqgAwIBAgIRAMc5w96+nYD4H/wN+uub9wEwDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTIyMDkxOTIxNDEyOVoXDTIz
    MDkxOTIxNDEyOVowKTEVMBMGA1UEChMMVmVsb2NpcmFwdG9yMRAwDgYDVQQDDAdH
    UlBDX0dXMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4jpeRodm6Rjz
    Xva+AiyPC1JzmdK0HuOmEnmr4EO8RKbPCxB1ZMe9JN81gmRbV+ii6F+aTNyYc6AY
    rIlh4iMaVgjT716WpYWfLArNxWrPsTDz4X1ZB6Zec9ezfr/T3r49DVVfjWHiJ/m3
    L0/dxZVWSdYSyOefd1xqi8wRmmafnl3yjoU2RRuhOjXKo8ZHci85sYXtAI22+Lin
    7AIGnq7xfJ8fmJ4+UWLKWRRkWJ5sdtU2vUFGBQypD8wsXV6HrNJfEtWOI1bQ4TMZ
    4bcljM1LMe7SU+EzCl5avJo8HQrn8RraMMCy83uo1PgkwFHfc+stawL5Vpp09CYt
    S/U1TSqxqwIDAQABo3QwcjAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYB
    BQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUGLi49E1t
    uyWnGnHmUKeFQ68im+4wEgYDVR0RBAswCYIHR1JQQ19HVzANBgkqhkiG9w0BAQsF
    AAOCAQEAGHx7ThiUoldC+ayRt+GY+goC5ELUNAM/EV/D5eX+yIj1d4WIAOoXfodu
    TVf+Zt4NO2S15CLwTgyRWfL7vTOMJ6eWNDqZ46zTphc7AEOW/2CQQj089cIlf0SA
    NNEkB/Lu6YrGlAxqhaHNT62xKYXzRUdK8VYauBCjOYYd3vAKUDLGd16XDZ2AYEBq
    dNZHVnP8xQLKWv5foJo17yghVRzfcjf+SL4OAPjPtgHz/Cs3YUh6lLo0eC8HYFjJ
    5i8nywvBtcqpgW+wpAH2j0OC6jF8IZaXDpA/PlYnAmyDdzPSBj8HjxIKJDk3ir5d
    myg/qUeBlSj2m4YYnt/78REhGz6E7w==
    -----END CERTIFICATE-----
  gw_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEA4jpeRodm6RjzXva+AiyPC1JzmdK0HuOmEnmr4EO8RKbPCxB1
    ZMe9JN81gmRbV+ii6F+aTNyYc6AYrIlh4iMaVgjT716WpYWfLArNxWrPsTDz4X1Z
    B6Zec9ezfr/T3r49DVVfjWHiJ/m3L0/dxZVWSdYSyOefd1xqi8wRmmafnl3yjoU2
    RRuhOjXKo8ZHci85sYXtAI22+Lin7AIGnq7xfJ8fmJ4+UWLKWRRkWJ5sdtU2vUFG
    BQypD8wsXV6HrNJfEtWOI1bQ4TMZ4bcljM1LMe7SU+EzCl5avJo8HQrn8RraMMCy
    83uo1PgkwFHfc+stawL5Vpp09CYtS/U1TSqxqwIDAQABAoIBAEipqsJIl1tjcjgc
    VKdqHH/secj8jnIleKASiIw99Wivk2zgWnSGW1BOiWdaSKSRylGM84igii8JSyOP
    9Oqnj7v2lewam5SKuLdyuOkiB5fIO20/z6rPWyMmMzcQ8kJnJED2HPzSZculP5to
    sbjW4KJSqjHxg5zZCDfi0fyf3cEFnUdUogtaDje0PlpcGekAR7Rx6rvq72at/fEU
    pXYVZlRRuDloxShlo2FBtDsTzuOLb0xR10VGtOOf/NhdLF2LLo9X22sxCffs3MbU
    Ye7H9Z4yYuvagGqJpu5M9B3zHvy3BYmoK3nZ2npAo+GLQke3hiR0mCvnobuN/pYe
    T+0tKZECgYEA+LCc4oACIH7mGWcFJZkWbfUP4u1Cr/xVc2aPdg86sZEoTXZw/Z4A
    YEhQQLQII6U5ZL+Fq+sJhHataguVhXLNhV2HMyOfjIOXKGqV2mcSEfiOM7az/me1
    c6Lox2THFRZfPf1cXNc1QabgvI0ZK1T2XzPgi83t2XS/i1RW97eFggcCgYEA6OC6
    5j5TDnDN4SuyzXt5pEBFsfR61JGkHaUC/QIHi4Tq6Hj/eEn7pvWh/vRLDb75KW96
    Uus3C9uJJG8xB4tvBOyDqYyvyShhVynqJNlJC9wZN8Xy8tpugnPDR5btZHp8iZXa
    6/bmDjR/xowC1IgbbqaAL4EKCV/uInbp+2IqGj0CgYEAkrtCFbIJjzrQcPSD6Ocm
    gMIzGWV8D3IGyQweYT4jF1naObpEeJ+dATIph8Oxebam4nbOW91VxD5xmzwygIZ4
    FNRWTSobnUCXE1WwDSj7VHcfEAwgr15phUz9o4gmnp6Qm3a95FlmJtJbj2SBETwU
    EZ/+QP7D86Yazg55MbeqokkCgYEAvNn6V1t1iYFrRE5muwKGG/BPVMgZkCbnu26k
    5L7vlXJd+dad/lOo87XBAHvmHaigcLzJq1K6mjAXoGdXkHG/v3N6NlYz++J2RfRk
    wCtBdI+yF6u8oLsI4Vu1omm/7Dr0obLYDYF1AVILyNykMuyJqor16xAvLnkQKfzb
    NRRfZlUCgYEA8jtNbhLEbdUQhXfYlIpVaDtDuyk54Jb8qVnYErSwnbHPfB+9HGCD
    a4UIFMAqbRgrcW5PgFoaqOGIYFi0J7PpCKPVYe7jlnfYaWeE56tpSHRptaWihH//
    3tsoUPrRS082fuGtENBszDBpgS00u3E3YWAEQsvSKORXogHe4Ev1gYI=
    -----END RSA PRIVATE KEY-----
  initial_users:
  - name: admin
    password_hash: 103df45196ca55e2fab5864ff17d9861417173007dc3bf78df43400edd0350c1
    password_salt: 35a8c0c1e366dab4152dd868332c482137caaa038d9e55ba16f97c54754ac9df
  authenticator:
    type: Basic
CA:
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEAxFYqfhSAsdcKl/IYEyKFT4i3CMUDu+FmDBy1bA/OsMa18GQ8
    HfwDNm5tP+Q9zsKXJmVgxDtCONKq7PnRXPYUAEWUYxAigFP0wgXwppXl4GwigoBJ
    3foQGp7jKHwwDhfCKMK/fFenFpvKNHShncvZa7cYlV6xqOZFVjMQZhdAKv974vtU
    7oGUI+KOF3CItCISQt2awZJdt4J3b3khp666tDMVe3FxCpWyCY4peb1ILOQpKi3g
    qD4ELuzi/xbQdBg7t99cdXer63Naqymrhmxx+3c+LsNUtCi1R/YCNuFst3RNdVky
    jyCmtcPb+OgwK9CDgmeFiFKj4VAo+csucpJjawIDAQABAoIBAQCxKErZTyi8z5vo
    dPNSOMDvfh4iFJuE6SJKZZEyO6U2D2dVzSwNpjtD3ypHD2zR5vW6GJnTFuFvInBG
    ujg22Hg9sortRD7NanQcqn114yX0db5B4P5GBICJdLrl6gD2hmuUmf1sdi73kIVJ
    BcBbAPhjYGgXR8Wo8Ha6DAONCwfEgwSwJk1I7cNfsPnq3yKho4wpWIqFQkmHarJa
    tBkEgx/jaGZ+gvpGGPPXyTilDtGe3REkcfzRVfujC1SqzzhutuashTqUEENxnlD3
    QKRD45l7xbSXBnioZQ+Nal/gpduQObwSXICl/Ie+uNUJrI/zLunUKR/DactgE22U
    kr3U5x05AoGBAOB+3Qa09U515kzr0qtDMledHeZE2JdkhAw9jLVHpV+KV99xGSRt
    j746O1V4JDDpnMNr+aw2iiO4FGmk8KSgM+L7Cl6bT5irR1Z2w68rKXzIlK9CkyZu
    BYdma6HAobUgPbNFAbRpaX9UjKInp+PJW7rQ9UG9QdtULPIpzuJ/3IptAoGBAN/j
    rLi/2USRxXEFNFvfcsegYc/vNprFR85l/vzVdTRmDQWaTVE8i2EPQU1blIijbdbx
    GsrC5TYKlHCC9bXgwJHHsa7n5dEELAXGD4BlOBGNeFn5jl6vxtuH/4rBxDdgQ1U0
    XqGhcsgS8qVI1/pXTP2zz2sRkQZLDhb2oldM6343AoGBANCre11BlQbSNjhnt1Fz
    y3Z+14zzj3PhfZA3IfRa3U/aMuXBpcIjiMokLIS8gL9qVkmbst6tb2fWMjskkn4j
    Xzdra28W5DyfcFbhW/EVqKGRfAsQUeEVwVPjEsauXGEUz+UzjmsY1HQDrhkHzVnB
    D9+tXVs2xOFO89xAmkoU2XVdAoGBAKMdWeJEC8P0PBfqhcoFkrcz9u8qResengEW
    uF52GezyCLyzPW9ZH+a32YjFlwKxpr25bR6aPapQrPMHxoIa29GZ3q8iToIoevY9
    5V9S3zWSj0NmGL6Na+DXRWtPXmhF3uh9vhAd8uUnQNcAqjG+Vt5jmVNVOgaOuhYq
    2/2kkdGjAoGAZbS/gEHqsLS0b6bX9bsHrZ3F0V4ij1DJEGVRMNJtC4l+gNRT7ZRI
    3KswqUqgyvuGHzzhY5f29OYSmTCj4K95JOld0ILfWmcrAYo6GpjV4630oMxuaxPY
    eE3xMY0ZTF6xqF+keNNPOJCHPwD+bgmrHhCvfCP+YNBElWqedI/y9AA=
    -----END RSA PRIVATE KEY-----
Frontend:
  hostname: localhost
  bind_address: 0.0.0.0
  bind_port: 4200
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDWDCCAkCgAwIBAgIRAJKdf9Eo/A1Xo2ks0R8U0pcwDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTIyMDkxOTIxNDEyOVoXDTIz
    MDkxOTIxNDEyOVowNDEVMBMGA1UEChMMVmVsb2NpcmFwdG9yMRswGQYDVQQDExJW
    ZWxvY2lyYXB0b3JTZXJ2ZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
    AQDyXnWQkG0fDD16+pnaTuLdd1p6ljIzG34X2uLRWDwPWQQhaX9qbPGc6slGxooC
    1iE6xp5OjEZptQOSDpSnzqC4Za4yuQ3+zVwhi0ThvXUQm7auGouGgLKOa+nM2+/j
    6lrwYQbEkn9x9H/eiNRqK5paN0r42tLUkb2by64X9V3qhZjIpF0OK8Q/Wb+isiWH
    W9aIfCJcGJpqATv9awk7omDrBzrJz7T+/uH8770Sds6YfgIYR7rRBwkHk+flCm3l
    9gIlEtoSP5cX/wdz+lQ9aBXckbxXl6+fbkfc9WIZTGrUAXeBa09ivT4rMaDe7jmK
    4LRM5IrUU8/06Ckexn8HyBoFAgMBAAGjfzB9MA4GA1UdDwEB/wQEAwIFoDAdBgNV
    HSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAfBgNVHSME
    GDAWgBQYuLj0TW27JacaceZQp4VDryKb7jAdBgNVHREEFjAUghJWZWxvY2lyYXB0
    b3JTZXJ2ZXIwDQYJKoZIhvcNAQELBQADggEBALyGWc/FcyMYbTozh19qzn/WixHd
    E5s+40JB/f+mA0wl72AlI2G1VQo4pvoFCFrdEPBu2x1ruqsd4sNswQ/4QcOZuGmS
    r1y5GmvPW78zXd4V2Eaw6ys9EC8srtHr50s1GBEpVONjnlI+pdkmtGe0Q3wsXfGL
    nMtUwqxGXCFFVNrq9nbrbCBnpQCNzu3/HMm7nEWIjbfznX3nRzS9vdE8m0arwEEV
    wkkaVhcv4oaa2SA98p25rS5ern5ynJCwru3upFBbF0UKr4hOzjjsBOv39f5rRDPK
    dqbByrHkC7ZUl6SaU3+kSt7HTIVq5lMBfyzxtqEbn3+eT0JTxsT401fo2BM=
    -----END CERTIFICATE-----
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEA8l51kJBtHww9evqZ2k7i3XdaepYyMxt+F9ri0Vg8D1kEIWl/
    amzxnOrJRsaKAtYhOsaeToxGabUDkg6Up86guGWuMrkN/s1cIYtE4b11EJu2rhqL
    hoCyjmvpzNvv4+pa8GEGxJJ/cfR/3ojUaiuaWjdK+NrS1JG9m8uuF/Vd6oWYyKRd
    DivEP1m/orIlh1vWiHwiXBiaagE7/WsJO6Jg6wc6yc+0/v7h/O+9EnbOmH4CGEe6
    0QcJB5Pn5Qpt5fYCJRLaEj+XF/8Hc/pUPWgV3JG8V5evn25H3PViGUxq1AF3gWtP
    Yr0+KzGg3u45iuC0TOSK1FPP9OgpHsZ/B8gaBQIDAQABAoIBAQCcUMfKQRvf1mkg
    k9f+sLoo0/2K6qvdwnGEuStokVvLGkJLulrvLOx3pAXEm/AO/EPaQJeBWX9gVdrD
    rJu7zsxhoVLEbA3WtGQjTktSvHpwB72+dGhgi0ieCoN0GLWTbWbRegJ/bWy89lAy
    GlXFU/HtFZRJA/jOGGENxkO2OA4mXlpoRdLIEjgJiAZaDKQlRbyzDsX3R/qElJNA
    pNYW06Nl7T2NF1PpdN5YZAduFRtL4bjqd50MCEdko1qd7Sr3+edzBTjkTa+UhwsN
    jnkwcpNOVZbLNotrYJnNkISLKwp4eQIcLKfWWQWWAQER+iaHWIQOUajJcwcqEaKM
    QASgJ0EBAoGBAPf/Ey3adEBLxZP7tJzA71ehU0AXGBAmiLt31E6g3+IN8xZ+1uo7
    EnZqyUo/JYva+wCfy+CZSVQkUllMnWuhJrUi0bPXgPudHF08ghnnCKxGTrRxGdvG
    0LLyZ3XCA5QXabvNEL5WYLTKFiQmAUFNriQx+S4w+bHCZ9jtcAUWLvWVAoGBAPow
    5CQksMFwg4cYIjMfkMAp+q2Qk5uCZF71/6MClV9iUd+rb5eR/P4C+3KkoUWkNpdJ
    C51WyozPz1WPDTAruu4PYZCS7+igqaN6ZdkAnOBQmwnVZ2DCYCkk7QXtB7uOwnPw
    WIHdSNEYY2u+8ELrfN5pbTh5OTb/mMc0l8LW/5axAoGBAJziNUzVnKMsDAKQwfJE
    L2UdPmAV+/gDmI4XwSw4o0kLEBPUC7tDwWs+JLaeee8eiZkcfcpIzlW3YIzzZca3
    vJfsPgLqOsNx4YauB5PBTwBEvfdycSxSeqYpqP+ay868fPv8PzJZzHWyPg2CKVsZ
    fCeToZHyE5O7axyVID9niC99AoGBAPmNruKGXnB0pB0qa2KHB8FFni9l2HXzF97I
    jVaxiwD7dyMdQ0/yZGGR4/G0WNC4PWOljppAKgVOe0aiS8tSs0Alw3GLvxVQvCS+
    P7y2KcRtYlfqrxUKjRQ9KtcQWPgyK6+tevr+GFXId9LPP6PgdEr86d68u98qD+AT
    i5TjE0nhAoGATZAIzMX1ZmG+TkBh9eoFkc+8qipIv1NrXGhzuHCvg/A7t0KAzFFU
    ilw8fSTSYjwo6wSQUvJ3is/cjZjpiOq3TZdAiAMr0SHbqFNi9s2eTq7OiUhAHb+E
    Cf5IJnInOY7wvxPJu6Yau9iOdBtSvVP7GmxxSI+5SZ2Mr0gVpi1u+4I=
    -----END RSA PRIVATE KEY-----
  dyn_dns: {}
  default_client_monitoring_artifacts:
  - Generic.Client.Stats
  GRPC_pool_max_size: 100
  GRPC_pool_max_wait: 60
  resources:
    connections_per_second: 100
    notifications_per_second: 30
    max_upload_size: 10485760
    expected_clients: 30000
Datastore:
  implementation: FileBaseDataStore
  location: C:\Users\PRINCIPAL\Documents\UNIR\TFM\proyect\tmp
  filestore_directory: C:\Users\PRINCIPAL\Documents\UNIR\TFM\proyect\tmp
Logging:
  output_directory: C:\Users\PRINCIPAL\Documents\UNIR\TFM\proyect\tmp/logs
  separate_logs_per_component: true
  debug:
    disabled: true
  info:
    rotation_time: 604800
    max_age: 31536000
  error:
    rotation_time: 604800
    max_age: 31536000
Monitoring:
  bind_address: 127.0.0.1
  bind_port: 4203
api_config: {}
server_type: windows
obfuscation_nonce: 9pdVjzg3eFI=
defaults:
  hunt_expiry_hours: 168
  notebook_cell_timeout_min: 10
