version:
  name: velociraptor
  version: 0.6.4-2
  commit: b6c5764a
  build_time: "2022-05-08T21:40:03+10:00"
  compiler: go1.18.1
Client:
  server_urls:
  - https://prueba-velocidex.com/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDTDCCAjSgAwIBAgIRAOv5hoaDCw7LmKMxzT5lFnUwDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTIyMDYwNjIxMTkzNVoXDTMy
    MDYwMzIxMTkzNVowGjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMIIBIjANBgkq
    hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz30MIR+ne/jj0PJIQKbT+67KKh3Vl9Jl
    iGh12m/NbtOUotiAGEuqCIEFQAnx0eK9lqT/L3bNdoR0B+aWqrt3DepFZxN1sm+x
    EHLPZfkMfPqNgjiEF3+WXc6ubDcJHDZebYp4bCGf3PsgU1hm9VbmLUz66QnevrJn
    6WmCeMZoCjrteoAJ0yoLhqwy49rbI5qW1araLbZY4koC5LPs2WzJNRTprATBWaW7
    zlqXootCpJ3hNCy0UOeO4RjV2CEhfDqMSR/kSw4POJ6qa2abH0GxFjOBY/M0EYpQ
    BixZBi+CYTXCOChOiqu4REAtIKi7oA2BoXwRiNpiEh+cdMtVm6yaYQIDAQABo4GM
    MIGJMA4GA1UdDwEB/wQEAwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
    AwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUJU8z7b2wRvr3DskmaWCHnH8H
    LcwwKAYDVR0RBCEwH4IdVmVsb2NpcmFwdG9yX2NhLnZlbG9jaWRleC5jb20wDQYJ
    KoZIhvcNAQELBQADggEBAAaB5NHqXP84mchh4vRD6RudwwDuhnTaxBmwz46uSaHZ
    zcoipH4f7lqp35MKwDa709uPC5QOWOStmB89+35tl1/MlvXGCdXfan5o9UVRfnEr
    daiq3UCCZ0BV9QdcYI2EJQT5Py+fIuQZn4hKEonrPTggsSsND9TFualPMNqYyeij
    6atNDbkGEXZHW0Az4AhbdXwCo/F0h+36XoFqnUhTKxzAnpIrHyKmElcj164Elxmb
    8iSDmtJwk22IyVGQwhHpBzp9k7g2+u8Y70cmmv1sfzINS761joI81nzQWh4u3VhR
    Vk+bz5rZ213FOKO4KRkC+9Y11oV5/CHfr6GR41I5+y0=
    -----END CERTIFICATE-----
  nonce: y5feDh3NntY=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.6.4-2
    commit: b6c5764a
    build_time: "2022-05-08T21:40:03+10:00"
    compiler: go1.18.1
  pinned_server_name: VelociraptorServer
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
API:
  hostname: prueba-velocidex.com
  bind_address: 127.0.0.1
  bind_port: 8001
  bind_scheme: tcp
  pinned_gw_name: GRPC_GW
GUI:
  bind_address: 127.0.0.1
  bind_port: 443
  gw_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDQTCCAimgAwIBAgIQLUU+6FNLG65ZkR/wVbAhwjANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjIwNjA2MjExOTM2WhcNMjMw
    NjA2MjExOTM2WjApMRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxEDAOBgNVBAMMB0dS
    UENfR1cwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDvtLCFRn7o4ZQ0
    Ml9z+d3ME7XXN/bAfgcGok/yb8cx6H+p068CHXogYZQHMH3ifV55IHMb+y3HQdw/
    Xq1nyLgjdfIDvATsXaDSS0KblSjXhAAedqSHo++YmE8qQ8nkKfH2oBMlsfbxhdLW
    ZNcy6/oaZf2t3GWUkTKouxvsSrxkBgBN9yYhOjM8LMR3Etu5D4LI5kskhv3RR6Xh
    D0KZeHvy5L+pp501bkhXItI6dHtzmB/prqLXvdspF8iXyu8xQg3xhIFyrcx6vcI8
    54xofL6ic3uWjAtmA994iHyqdfwqb8GBUXvCN/ZlWcSJuQLbnm2/4Qkziuod7ogb
    Isa8KED3AgMBAAGjdDByMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEF
    BQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBQlTzPtvbBG
    +vcOySZpYIecfwctzDASBgNVHREECzAJggdHUlBDX0dXMA0GCSqGSIb3DQEBCwUA
    A4IBAQAE7O6ptiJj8834Xl4iAR8gkgmprywV7iJcATd8svdSmfE947qnt2EPkto2
    UTAX68mTBdoPa3DzC9Isc3+Ncg+U+xyXj5uSfHC45uWVDrhjpwBsFRbw5z8j+RGj
    XOxnbAfvHaK1OHfpWbiBnz3GstLV41338v0XRQLPO73hOEVeDshjRJq7iRqFX3Xa
    5yxtwE7Fr5K/5hkCHMiuQlgyEW9Tp63OwqrrgGtHawZmDT+MC0v9JWPXkiluFORs
    vT1mf0s6yHCzfYpJWEQQrTig3AFmygpXv0Md3dkWFBKUyALaiEffjhJWT1k2h0eC
    8PphPtu59bJc5ySN90Cat06EkCkg
    -----END CERTIFICATE-----
  gw_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpgIBAAKCAQEA77SwhUZ+6OGUNDJfc/ndzBO11zf2wH4HBqJP8m/HMeh/qdOv
    Ah16IGGUBzB94n1eeSBzG/stx0HcP16tZ8i4I3XyA7wE7F2g0ktCm5Uo14QAHnak
    h6PvmJhPKkPJ5Cnx9qATJbH28YXS1mTXMuv6GmX9rdxllJEyqLsb7Eq8ZAYATfcm
    ITozPCzEdxLbuQ+CyOZLJIb90Uel4Q9CmXh78uS/qaedNW5IVyLSOnR7c5gf6a6i
    173bKRfIl8rvMUIN8YSBcq3Mer3CPOeMaHy+onN7lowLZgPfeIh8qnX8Km/BgVF7
    wjf2ZVnEibkC255tv+EJM4rqHe6IGyLGvChA9wIDAQABAoIBAQCg/cpQuLgj0N2o
    8OwLCJZeqh5HHd8sCXjOi9UGDuzKKE0V0oaH9SRA+0hgS8FAjNMWpySodlqYqTMz
    nHL6cWS67ExPFch4t6l7k/B4bgWwOYea7jQypXgWFLWWvVCrXUCVU42Ik643KJoi
    RDgEi1i+wiFO0+elkJ9lk8V9PfSpd9F8gGB39WrVFbnf2NlddWZXkFmmBMgVWWyl
    TlqoeNr8bNeMs2MH+9ussdha9cMT1M/06yaGfBFPQ8nIjcYAJud6Hv4FewNVbU0n
    DGmUjMJfUQnyZ4b5VQfMZ2owCA3j24YN7G7ZYtsWMOtSieOj3VYIM/f4U2w5nkY7
    rsULwUEBAoGBAP6RZRB7yU04Un5ea7kodnnbAQX0Ty6iyPclwDJnrtEZ+BT+XE+m
    khu6QrM0JAj7tXXLfLmA4yjWLXkeERH0SzrECpfyImxgesLu+bEdylp5VA9rFKjM
    VpIzAvwhL62SPPoYR3NxMm9aYStOhaAJ3b2JjbWiEtUaGAxEr/ZFcVT/AoGBAPEN
    5EWFrJ/5nPSLv6YEjdiOqMavzvHtESSMn47OMj5P5iErF0keRHhPvt7VeGFKPdai
    vJfP0DqWKneat6Ol24PLQ20m4MAiikOVP46bbvpI1dqD9H4MET0SQGpYaBlL7guQ
    8jqIkRZMUgSBhYT7/rMoZt4PB6SGtUNjHybaP7wJAoGBAMdPMLCCKm5yDWxxIqg6
    POBVDm0KBcC+pNeTz/Hm6aE/UtOk/sNB6B0bbMN/rEL4R+9tHT7j4XaEkd/FIZpM
    CWZ+PMkQQ9FUjGj4z7fTWi4R1jWoIemy6ojWtZyPoxOjbmhk//QriVBTk8ZjWQ2f
    C+QswS2XMmV0Y6WfVaFcZ0ojAoGBAKClfWfHuk+y7qMbL1HY3x9fk6M2L1iTgUU2
    Ym+tg1Z7sQaRzSbxgPgdTTr8UQmljKiqM72IxWEGCq9C8Pei5TRkFj98FXR2kGaR
    5JWJiOBMAhlqr1oBeMuWik9VM6sIK1CR/Jx9vxN5MX/HQdBqkEeduVBr+8/t5odO
    W8hs0uThAoGBAL6kG5DWhz/v6XiQp5OupYuMXdiYUJd6hLU2XmMQCt0OLCAXzMkw
    mnQ3Br4zQgvw8vHOUf1ybidaV5ShiVWI3TykEoRLm0uvWQk+MWRgA8Bj/GYZf42d
    EBprMgXzOLU466CtjBpR8kfkdFI7jknw+ui2Ff6iLYIOPB3boxITUBcM
    -----END RSA PRIVATE KEY-----
  public_url: https://prueba-velocidex.com/
  initial_users:
  - name: vasciber@gmail.com
  - name: vasciber@gmail.com
  authenticator:
    type: Google
    oauth_client_id: 453560071384-13sqdb3n3fgss2243td7inbq487vsa4e.apps.googleusercontent.com
    oauth_client_secret: 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
CA:
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAz30MIR+ne/jj0PJIQKbT+67KKh3Vl9JliGh12m/NbtOUotiA
    GEuqCIEFQAnx0eK9lqT/L3bNdoR0B+aWqrt3DepFZxN1sm+xEHLPZfkMfPqNgjiE
    F3+WXc6ubDcJHDZebYp4bCGf3PsgU1hm9VbmLUz66QnevrJn6WmCeMZoCjrteoAJ
    0yoLhqwy49rbI5qW1araLbZY4koC5LPs2WzJNRTprATBWaW7zlqXootCpJ3hNCy0
    UOeO4RjV2CEhfDqMSR/kSw4POJ6qa2abH0GxFjOBY/M0EYpQBixZBi+CYTXCOChO
    iqu4REAtIKi7oA2BoXwRiNpiEh+cdMtVm6yaYQIDAQABAoIBAGjTTkt1yJHzfnVT
    0nkHT9W5yt1YUU7wtuchj1kaXvl8330eUCj2ISNGu7ZMz+Uv3oS7O0lphgg4hr5v
    GvOK3m0jTIj05eOOVjBvMKTeHBcQJmoBz4pnpTojby+w5mNgfHhvGsPWgQONxBkX
    cnzEuGlumN0fZW+GhsT/zzDhXDK+BXVIrbaByDd5LOpSCPh733DQIfPloh8HuuJn
    0dHfWVczuDpDgfZ8y6qxYPw5bD9xXcWs+vH91Xe03soEOTXzxqB/YCFDF2CpEVJd
    5lUX8Yzcc5FLJ8YOgKquiCVrTXeZL3fIFEV3A0oZTwTsqMxSH+3AEH2dm2P6sert
    YpKahyECgYEA2ZUw1EiekvJRDsF3Rblqfgf+Z/RzEmCyxwvbSSPwQnzS4jyIY1yj
    ha6dDDgvNGO88qoJBulYNKhauCR+s4RF75rJbDFVSc4Nd/508iq25FrH6V2Rfz0z
    5KjalrKAeNmmHvw24VVzlbymWeWyym9b3pRpoj+sreQRD94c0jt4qC0CgYEA9B+X
    NyfcJ45UdTbDPztrXpXaccpca0n8GoGoMLVegIO8PgmhC4lRzSk2JdKYuzET698u
    8g4wlIXjUU/2tlJJSUiePxDWEdrUWwWbUj49VmnxSfN+uSpUHBbD38UdEcPBf+B6
    tkrbv90Acswmp5dhbN4X+AR9CjESUrYUBSl0B4UCgYEA1aN8b2Pid8x/tGpXz1lQ
    a/EzZiUKe8gAohpNNRKZjN79PXBMRqumT9N0lpPwHZO06dv0wxmJJyMK+HW1BlTh
    SnOERLxnzvEIHoL1lvZD4BIW6leaTgHtGx6EiqU4KfEjAJeK11PNCwBRokE8fTI8
    VV8KHWpCBffCnP7s86u7O/0CgYAx1SkHB0n3gSRYcP9WLwjx2+EljUtkU0v1FTaC
    CuPpk/qfJ1QKiNN778ev3Nd0jsYkRgDNRHxCNTp75LjV6uIu5XX4JbWtG2Bx3Cki
    lrXqp+GrWNsrbSqSOUtuqEwQzkb3lZk3EPzeo3xt8qKJX2txz7xQ0om7xNyaqbRY
    gWfACQKBgCPlLIybbmGa1ClTpm4+IMPQYlhBPqtWwr2CNi+LdM8PdU20CJoLbg/6
    zEQ0BVju0M1G0akob/ia9BwrZGFW4wZavP78npQZ92QDxwXR5haHZP34+YcX5jP4
    +4WiQ441CzM+Vj06zz1xyyC3DlgXaKNpnCUPk9QtpHZ9DQDofqRn
    -----END RSA PRIVATE KEY-----
Frontend:
  hostname: prueba-velocidex.com
  bind_address: 0.0.0.0
  bind_port: 443
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDVzCCAj+gAwIBAgIQPKHDXEGCu32PdwxhUbwbuzANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjIwNjA2MjExOTM1WhcNMjMw
    NjA2MjExOTM1WjA0MRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxGzAZBgNVBAMTElZl
    bG9jaXJhcHRvclNlcnZlcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
    AL7lMLF6yo2ueDJI/fVepzDNScXShf3Qthj9DSZ64tW3vmoopJgYnaCNMIn9XgeY
    QPuZIeiYIhUxK6JPwu5yArPtycLoGycoBCLbVEK94SHVcfzjkHVbFXkIUfo60NsD
    7bn18ydWrllXNDW8nnsaVI5FDZriqkF4si3Wn6BNvyCFo4c+oafX4yzkg9N2wjES
    Ak7qjsFrGL0h/7iOg1APAy6mt6CUXvaa3QF9IlIZqJk+oaBBX+04nUTMJX+PF2z2
    cU3MPETsFZwfn9d5152NWRqeDmTaDuA3wrCUvjNESbEcIe6mkFxUQ5mMxmc8W0ZB
    LxoZgiQ464Da5SZ7mKI5owsCAwEAAaN/MH0wDgYDVR0PAQH/BAQDAgWgMB0GA1Ud
    JQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB8GA1UdIwQY
    MBaAFCVPM+29sEb69w7JJmlgh5x/By3MMB0GA1UdEQQWMBSCElZlbG9jaXJhcHRv
    clNlcnZlcjANBgkqhkiG9w0BAQsFAAOCAQEAABhKiuIrm5h/DSofWTYQRH3v6MB8
    RSqXU4baIq5nd7aN3AmdlZU+ERhBNf3bf3q2AgLkRyCzxITgypsjPsOo9x5QVaUA
    u/tz10pEJzZ00lAy+aFLaie2nZK8pACglHdKHmkZYdar1rCctqw587+BzwBGAj/E
    DMzTkrlLBCaC/K9UyKJkvmyGQlr5R8eKlX9bDXCO8GSVKXgXGNwegZ5lTH2ikuhX
    Bu3rCI27RXbxHbV9nlzCtiiCWl3T/PH/b+cgeS8IDRbw8Eq8Osmj8/DnufvIqwJt
    zs856imI54MW9w/LY6iWBVylTX8EAdtI9AK0XNSe8GYjisMqkOofWEuwJg==
    -----END CERTIFICATE-----
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAvuUwsXrKja54Mkj99V6nMM1JxdKF/dC2GP0NJnri1be+aiik
    mBidoI0wif1eB5hA+5kh6JgiFTErok/C7nICs+3JwugbJygEIttUQr3hIdVx/OOQ
    dVsVeQhR+jrQ2wPtufXzJ1auWVc0NbyeexpUjkUNmuKqQXiyLdafoE2/IIWjhz6h
    p9fjLOSD03bCMRICTuqOwWsYvSH/uI6DUA8DLqa3oJRe9prdAX0iUhmomT6hoEFf
    7TidRMwlf48XbPZxTcw8ROwVnB+f13nXnY1ZGp4OZNoO4DfCsJS+M0RJsRwh7qaQ
    XFRDmYzGZzxbRkEvGhmCJDjrgNrlJnuYojmjCwIDAQABAoIBAQCup1DiwN67vEn6
    b+/y5DQBoYGCvfeb3q4MtNGoSDxrnx5XUHIvOi5Vq3gieC7ksfeaemOcxDxCuWcb
    rPBDawpwBvpXGjdlnuYR4iv4mHN3misdXjNYPAqsXuFqGQ/nonOJda6Pam5ADVoW
    ZEl3hgKg3Crzb7ioCD61U61eZGOe4y9eBpJsiBha/zuL75XO3lnW7iASr7/UkMn0
    x3eRo1aaRAHif785vlGle0xLTx3+pUl0zsJ0bBy2khcox+YdxALhoRPxy2zepYom
    CtVI64aPOGyzxCtNZJ8ANiRZrU5MY8mRGrn+mh+LRPSFZr67JNyFVBOXJ8JPpVX7
    Qw/vRkpxAoGBAMX+ve/NCe4unDM02nibR1NMjkMs7+SUowY3U6YHODv6CVAKTT/H
    16Z525lfVAZ6Ie45X+4egwds9s+b9x6BijameR8CHqugdX7K1cu2cOPsRk/RFxL9
    jowNp+NPws067A8QLMSrVr8r9YpAzo5HDntlnK+WDZkbSOS/GYoAIfV5AoGBAPbR
    +c3YP8oSe6PLzmYjIGx+kCFpWiSr7IFDGE5Y8ZbWtcyxm6u1kV6wZD+BzzIO6It7
    cPyA9vIU23jK0nSh5NaMrvtQrkdEltLUqgstkyizB03hVFUfdDK1kbrdSE0nPb2J
    Qr68ieRDN/wPXCeT6+lrBmfUxGjEU+vUxBUsKk+jAoGBALlM40gFljCi0K8f3QOZ
    F5S/BjmaWd2MulI7/35YLWn8ZTDSo1940bvNOhd9Xy88qHrCmaRKTAjsEsVUS1/y
    jn79KEg7/KZVYwFKJfMkiNzXKSrUHgs44Gr08NZNtJvMdFbYpX1eea4rHv7IDkib
    +dLE03KFNa7AGWVz8Bv2adHJAoGAVLI/L3TKhvQKu21feUsKgFB58w0s4rKgaMb2
    W0RIOsOZBRHZYnXe2YhcDjLkP8A/6kVEw1EZ7H5dxbiLuXwog7so/JJ2C3ys6NIT
    O9y6x9ePZRkykDdH73LA/Eec3OTfWd/1KHCYPN0YJAW9UNOAu8t/Gjg34d+lEKMl
    WkKajlMCgYBt4hURx2LQA+dlWzxCIrzll03+fSpsaUmFi/ts6Y/sEOZDeziUW2jY
    WveFuZEZd7rca2bxIbegde6+jN7DoOmmd4soQYQKdd0MInvMq9v0RXBJM2hcQkeJ
    5K4Nnr3YXnypJLs2UnkK6m0ANz0ldyI60nivJTNDeySibCMvrftjmA==
    -----END RSA PRIVATE KEY-----
  dyn_dns: {}
  default_client_monitoring_artifacts:
  - Generic.Client.Stats
  GRPC_pool_max_size: 100
  GRPC_pool_max_wait: 60
  resources:
    connections_per_second: 100
    notifications_per_second: 30
    max_upload_size: 10485760
    expected_clients: 30000
Datastore:
  implementation: FileBaseDataStore
  location: /opt/velociraptor
  filestore_directory: /opt/velociraptor
Logging:
  output_directory: server.config.yaml
  separate_logs_per_component: true
  debug:
    disabled: true
  info:
    rotation_time: 604800
    max_age: 31536000
  error:
    rotation_time: 604800
    max_age: 31536000
autocert_cert_cache: /opt/velociraptor
Monitoring:
  bind_address: 127.0.0.1
  bind_port: 8003
api_config: {}
server_type: linux
obfuscation_nonce: J+syndxcjvY=
defaults:
  hunt_expiry_hours: 168
  notebook_cell_timeout_min: 10
